import { useState } from "react";
import { ArrowRight, ArrowUpRight, Heart, History, Utensils } from "lucide-react";
import { CartDrawer, CartProvider, Footer, Header, MobileBottomBar } from "./Home";
import site from "@/data/site.json";

function AboutContent() {
  const [cartOpen, setCartOpen] = useState(false);
  return <div className="wilton-site inner-page"><Header solid onCart={() => setCartOpen(true)} /><main><section className="inner-hero inner-hero-story"><div className="site-container"><span className="eyebrow">Recipes in our DNA</span><h1>A table with a memory.</h1><p>Two decades of Sultan Bathery hospitality, carried forward one generous plate at a time.</p></div></section><section className="section story-section"><div className="site-container story-grid"><div><img src="/manus-storage/async-images/JZcAUBYQomFLFelj4jdtNr/image-1.webp" alt="A family-style table at Wilton" /></div><div><span className="eyebrow">The Wilton story</span><h2>Rooted in family.<br />Made for everyone.</h2><span className="gold-rule" /><p>Wilton grows from a family love of feeding people well. The story reaches back to the late Neeliyath Hassan Haji and Thoufeeq Hotel in Meenangadi, and forward through two decades of welcoming families, travellers and friends in Sultan Bathery.</p><p>Today, Wilton brings Kerala comfort, mandi, biriyani, tandoor, Arabic mezze and Chinese favourites under one roof. The menu is broad because the table is broad—there is always a little more room for the person who wants a familiar meal, the friend trying something new, and the family staying one night longer.</p><a className="button button-spice" href="/menu">Explore the menu <ArrowRight size={16} /></a></div></div></section><section className="story-values"><div className="site-container"><div><History /><span>Two decades</span><p>Of welcoming Sultan Bathery families and travellers.</p></div><div><Utensils /><span>Many cuisines</span><p>Kerala, mandi, biriyani, tandoor, mezze and Chinese.</p></div><div><Heart /><span>One warm table</span><p>Generous portions, thoughtful service, no fuss.</p></div></div></section><section className="section story-cta"><div className="site-container"><span className="eyebrow">Come hungry</span><h2>Leave looked after.</h2><a className="text-link" href={`tel:${site.phone}`}>Call Wilton <ArrowUpRight size={16} /></a></div></section></main><Footer /><MobileBottomBar onCart={() => setCartOpen(true)} /><CartDrawer open={cartOpen} onClose={() => setCartOpen(false)} /></div>;
}

export default function AboutPage() { return <CartProvider><AboutContent /></CartProvider>; }
