import type { FormEvent } from "react";
import { useState } from "react";
import { Clock3, Facebook, Instagram, MapPin, MessageCircle, Phone, Star, Youtube } from "lucide-react";
import site from "@/data/site.json";
import { CartDrawer, CartProvider, Footer, Header, MobileBottomBar } from "./Home";

function ContactContent() {
  const [cartOpen, setCartOpen] = useState(false);
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const body = `Name: ${form.get("name")}\nPhone: ${form.get("phone")}\nEmail: ${form.get("email")}\nLocation: ${form.get("location")}\nMessage: ${form.get("message")}`; window.location.href = `mailto:${site.email}?subject=${encodeURIComponent("Wilton website enquiry")}&body=${encodeURIComponent(body)}`; setSent(true); };
  return <div className="wilton-site inner-page"><Header solid onCart={() => setCartOpen(true)} /><main><section className="inner-hero inner-hero-contact"><div className="site-container"><span className="eyebrow">Find your way here</span><h1>Come say hello.</h1><p>We’re on National Highway 212 in Dhottappankulam, Sultan Bathery.</p></div></section><section className="section contact-page-section"><div className="site-container contact-page-grid"><div><div className="section-heading"><span className="eyebrow">Wilton Restaurant & Hotel</span><h2>Your table is waiting.</h2><span className="gold-rule" /></div><div className="contact-page-details"><a href={site.phoneHref}><Phone /><span><small>Main line</small><strong>{site.phone}</strong></span></a><a href={site.takeawayHref}><MessageCircle /><span><small>Take Away</small><strong>{site.takeaway}</strong></span></a><a href={site.roomReservationHref}><Clock3 /><span><small>Room reservation</small><strong>{site.roomReservation}</strong></span></a><div><MapPin /><span><small>Address</small><strong>{site.address}</strong></span></div></div><div className="social-row"><a href={site.socials.facebook} aria-label="Facebook"><Facebook /></a><a href={site.socials.instagram} aria-label="Instagram"><Instagram /></a><a href={site.socials.youtube} aria-label="YouTube"><Youtube /></a><a href={site.socials.tripadvisor} aria-label="TripAdvisor"><Star /></a></div></div><div className="contact-form-card contact-page-form"><div className="form-card-top"><span className="eyebrow">Send feedback</span><MessageCircle size={25} /></div><form onSubmit={submit}><div className="form-row"><label>Name<input name="name" required placeholder="Your name" /></label><label>Phone<input name="phone" required placeholder="7902 000 000" /></label></div><div className="form-row"><label>Email<input name="email" type="email" placeholder="you@example.com" /></label><label>Location<input name="location" placeholder="Sultan Bathery" /></label></div><label>Message<textarea name="message" required rows={5} placeholder="Tell us how we can help..." /></label><button className="button button-spice" type="submit">Send feedback <MessageCircle size={15} /></button>{sent && <p className="form-success">Your email draft is ready to send.</p>}</form></div></div><div className="contact-page-map"><iframe title="Wilton Restaurant & Hotel map" src={site.mapEmbedUrl} loading="lazy" /></div></section></main><Footer /><MobileBottomBar onCart={() => setCartOpen(true)} /><CartDrawer open={cartOpen} onClose={() => setCartOpen(false)} /></div>;
}

export default function ContactPage() { return <CartProvider><ContactContent /></CartProvider>; }
