import { useState } from "react";
import { ArrowRight, BedDouble, Check, Clock3, MessageCircle, Wifi } from "lucide-react";
import rooms from "@/data/rooms.json";
import site from "@/data/site.json";
import { CartDrawer, CartProvider, Footer, Header, MobileBottomBar } from "./Home";

function RoomsContent() {
  const [cartOpen, setCartOpen] = useState(false);
  const reserve = (room = "a room") => { const text = `Hello Wilton, I would like to enquire about ${room}. Please share availability and rates.`; window.open(`https://wa.me/917902534444?text=${encodeURIComponent(text)}`, "_blank", "noopener,noreferrer"); };
  return <div className="wilton-site inner-page"><Header solid onCart={() => setCartOpen(true)} /><main><section className="inner-hero inner-hero-rooms"><div className="site-container"><span className="eyebrow">Stay with us</span><h1>A comfortable base in Wayanad.</h1><p>Clean, calm rooms and an easy welcome in the heart of Sultan Bathery.</p></div></section><section className="section rooms-page-section"><div className="site-container"><div className="section-heading"><span className="eyebrow">Choose your stay</span><h2>Room to rest well.</h2><span className="gold-rule" /><p>Call or WhatsApp for availability, rates and anything you need before you arrive.</p></div><div className="rooms-page-grid">{rooms.map((room) => <article className="rooms-page-card" key={room.name}><img src={room.image} alt={room.name} loading="lazy" /><div><span className="eyebrow">{room.meta}</span><h3>{room.name}</h3><p>{room.description}</p><button className="button button-spice" onClick={() => reserve(room.name)}>Reserve on WhatsApp <MessageCircle size={15} /></button></div></article>)}</div></div></section><section className="stay-details"><div className="site-container"><div><BedDouble /><strong>A/c rooms</strong><span>Clean, simple comfort</span></div><div><Clock3 /><strong>24-hour check-in/out</strong><span>Flexible for road trips</span></div><div><Wifi /><strong>Free high-speed Wi-Fi</strong><span>Stay connected</span></div><div><Check /><strong>Covered parking</strong><span>On-site and easy</span></div></div></section><section className="section room-enquiry"><div className="site-container room-enquiry-grid"><div><span className="eyebrow">Have a question?</span><h2>Tell us what you need.</h2><p>Share your dates, room preference or a special request. We’ll reply on WhatsApp.</p></div><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); reserve(String(form.get("room") || "a room")); }}><label>Name<input name="name" required placeholder="Your name" /></label><label>Room preference<select name="room" defaultValue="Deluxe Room">{rooms.map((room) => <option key={room.name}>{room.name}</option>)}</select></label><label>Dates / notes<textarea name="notes" rows={3} placeholder="Dates, guests, questions..." /></label><button className="button button-spice" type="submit">Send enquiry <ArrowRight size={16} /></button></form></div></section></main><Footer /><MobileBottomBar onCart={() => setCartOpen(true)} /><CartDrawer open={cartOpen} onClose={() => setCartOpen(false)} /></div>;
}

export default function RoomsPage() { return <CartProvider><RoomsContent /></CartProvider>; }
